package com.stixcloud.cart;

import java.util.HashMap;

public class CollectionCountry {
  public HashMap<String, String> mapCoutriesName = new HashMap<>();

  public void setMap() {
    mapCoutriesName.put("MY", "Malaysia");
    mapCoutriesName.put("AF", "Afghanistan");
    mapCoutriesName.put("AL", "Albania");
    mapCoutriesName.put("DZ", "Algeria");
    mapCoutriesName.put("AS", "American Samoa");
    mapCoutriesName.put("AD", "Andorra");
    mapCoutriesName.put("AO", "Angola");
    mapCoutriesName.put("AI", "Anguilla");
    mapCoutriesName.put("AG", "Antigua and Barbuda");
    mapCoutriesName.put("AR", "Argentina");
    mapCoutriesName.put("AM", "Armenia");
    mapCoutriesName.put("AW", "Aruba");
    mapCoutriesName.put("AU", "Australia");
    mapCoutriesName.put("AT", "Austria");
    mapCoutriesName.put("AZ", "Azerbaijan");
    mapCoutriesName.put("BS", "Bahamas");
    mapCoutriesName.put("BH", "Bahrain");
    mapCoutriesName.put("BD", "Bangladesh");
    mapCoutriesName.put("BB", "Barbados");
    mapCoutriesName.put("BY", "Belarus");
    mapCoutriesName.put("BE", "Belgium");
    mapCoutriesName.put("BZ", "Belize");
    mapCoutriesName.put("BJ", "Benin");
    mapCoutriesName.put("BM", "Bermuda");
    mapCoutriesName.put("BT", "Bhutan");
    mapCoutriesName.put("BO", "Bolivia");
    mapCoutriesName.put("BA", "Bosnia and Herzegovina");
    mapCoutriesName.put("BW", "Botswana");
    mapCoutriesName.put("BR", "Brazil");
    mapCoutriesName.put("VG", "British Virgin Islands");
    mapCoutriesName.put("BN", "Brunei");
    mapCoutriesName.put("BG", "Bulgaria");
    mapCoutriesName.put("BF", "Burkina Faso");
    mapCoutriesName.put("BI", "Burundi");
    mapCoutriesName.put("KH", "Cambodia");
    mapCoutriesName.put("CM", "Cameroon");
    mapCoutriesName.put("CA", "Canada");
    mapCoutriesName.put("CV", "Cape Verde");
    mapCoutriesName.put("KY", "Cayman Islands");
    mapCoutriesName.put("CF", "Central African Republic");
    mapCoutriesName.put("TD", "Chad");
    mapCoutriesName.put("CL", "Chile");
    mapCoutriesName.put("CN", "China");
    mapCoutriesName.put("CO", "Colombia");
    mapCoutriesName.put("KM", "Comoros");
    mapCoutriesName.put("CD", "Congo [DRC]");
    mapCoutriesName.put("CG", "Congo [Republic]");
    mapCoutriesName.put("CR", "Costa Rica");
    mapCoutriesName.put("CI", "Côte_d'Ivoire");
    mapCoutriesName.put("HR", "Croatia");
    mapCoutriesName.put("CU", "Cuba");
    mapCoutriesName.put("CY", "Cyprus");
    mapCoutriesName.put("CZ", "Czech Republic");
    mapCoutriesName.put("DK", "denmark");
    mapCoutriesName.put("DJ", "Djibouti");
    mapCoutriesName.put("DM", "Dominica");
    mapCoutriesName.put("DO", "Dominican Republic");
    mapCoutriesName.put("EC", "Ecuador");
    mapCoutriesName.put("EG", "Egypt");
    mapCoutriesName.put("SV", "El Salvador");
    mapCoutriesName.put("GQ", "Equatorial Guinea");
    mapCoutriesName.put("ER", "Eritea");
    mapCoutriesName.put("EE", "Estonia");
    mapCoutriesName.put("ET", "Ethiopia");
    mapCoutriesName.put("FO", "Faroe Islands");
    mapCoutriesName.put("FJ", "Fiji");
    mapCoutriesName.put("FI", "Finland");
    mapCoutriesName.put("FR", "France");
    mapCoutriesName.put("GF", "French Guiana");
    mapCoutriesName.put("PF", "French Polynesia");
    mapCoutriesName.put("GA", "Gabon");
    mapCoutriesName.put("GM", "Gambia");
    mapCoutriesName.put("GE", "Georgia");
    mapCoutriesName.put("DE", "Germany");
    mapCoutriesName.put("GH", "Ghana");
    mapCoutriesName.put("GI", "Gibraltar");
    mapCoutriesName.put("GR", "Greece");
    mapCoutriesName.put("GL", "Greenland");
    mapCoutriesName.put("GD", "Grenada");
    mapCoutriesName.put("GP", "Guadeloupe");
    mapCoutriesName.put("GU", "Guam");
    mapCoutriesName.put("GT", "Guatemala");
    mapCoutriesName.put("GN", "Guinea");
    mapCoutriesName.put("GW", "Guinea-Bissau");
    mapCoutriesName.put("GY", "Guyana");
    mapCoutriesName.put("HT", "Haiti");
    mapCoutriesName.put("HN", "Honduras");
    mapCoutriesName.put("HK", "Hong Kong");
    mapCoutriesName.put("HU", "Hungary");
    mapCoutriesName.put("IS", "Iceland");
    mapCoutriesName.put("IN", "India");
    mapCoutriesName.put("ID", "Indonesia");
    mapCoutriesName.put("IR", "Iran");
    mapCoutriesName.put("IQ", "Iraq");
    mapCoutriesName.put("IE", "Ireland");
    mapCoutriesName.put("IL", "Israel");
    mapCoutriesName.put("IT", "Italy");
    mapCoutriesName.put("JM", "Jamaica");
    mapCoutriesName.put("JP", "Japan");
    mapCoutriesName.put("JO", "Jordan");
    mapCoutriesName.put("KZ", "Kazakhstan");
    mapCoutriesName.put("KE", "Kenya");
    mapCoutriesName.put("KW", "Kuwait");
    mapCoutriesName.put("KG", "Kyrgyzstan");
    mapCoutriesName.put("LA", "Laos");
    mapCoutriesName.put("LV", "Latvia");
    mapCoutriesName.put("LB", "Lebanon");
    mapCoutriesName.put("LS", "Lesotho");
    mapCoutriesName.put("LR", "Liberia");
    mapCoutriesName.put("LY", "Libya");
    mapCoutriesName.put("LI", "Liechtenstein");
    mapCoutriesName.put("LT", "Lithuania");
    mapCoutriesName.put("LU", "Luxembourg");
    mapCoutriesName.put("MO", "Macau");
    mapCoutriesName.put("MK", "Macedonia");
    mapCoutriesName.put("MG", "Madagascar");
    mapCoutriesName.put("MW", "Malawi");
    mapCoutriesName.put("MV", "Maldives");
    mapCoutriesName.put("ML", "Mali");
    mapCoutriesName.put("MT", "Malta");
    mapCoutriesName.put("MH", "Marshall Islands");
    mapCoutriesName.put("MQ", "Martinique");
    mapCoutriesName.put("MR", "Mauritania");
    mapCoutriesName.put("MU", "Mauritius");
    mapCoutriesName.put("MX", "Mexico");
    mapCoutriesName.put("FM", "Micronesia");
    mapCoutriesName.put("MD", "Moldova");
    mapCoutriesName.put("MC", "Monaco");
    mapCoutriesName.put("MN", "Mongolia");
    mapCoutriesName.put("ME", "Montenegro");
    mapCoutriesName.put("MS", "Montserrat");
    mapCoutriesName.put("MA", "Morocco");
    mapCoutriesName.put("MZ", "Mozambique");
    mapCoutriesName.put("MM", "Myanmar");
    mapCoutriesName.put("NA", "Namibia");
    mapCoutriesName.put("NR", "Nauru");
    mapCoutriesName.put("NP", "Nepal");
    mapCoutriesName.put("NL", "Netherlands");
    mapCoutriesName.put("AN", "Netherlands Antilles");
    mapCoutriesName.put("NC", "New Caledonia");
    mapCoutriesName.put("NZ", "New Zealand");
    mapCoutriesName.put("NI", "Nicaragua");
    mapCoutriesName.put("NE", "Niger");
    mapCoutriesName.put("NG", "Nigeria");
    mapCoutriesName.put("NF", "Norfolk Island");
    mapCoutriesName.put("MP", "Northern Mariana Islands");
    mapCoutriesName.put("KP", "North Korea");
    mapCoutriesName.put("NO", "Norway");
    mapCoutriesName.put("OM", "Oman");
    mapCoutriesName.put("PK", "Pakistan");
    mapCoutriesName.put("PW", "Palau");
    mapCoutriesName.put("PS", "Palestinian Territories");
    mapCoutriesName.put("PA", "Panama");
    mapCoutriesName.put("PG", "Papua New Guinea");
    mapCoutriesName.put("PY", "Paraguay");
    mapCoutriesName.put("PE", "Peru");
    mapCoutriesName.put("PH", "Philippines");
    mapCoutriesName.put("PL", "Poland");
    mapCoutriesName.put("PT", "Portugal");
    mapCoutriesName.put("PR", "Puerto Rico");
    mapCoutriesName.put("QA", "Qatar");
    mapCoutriesName.put("RE", "Réunion");
    mapCoutriesName.put("RO", "Romania");
    mapCoutriesName.put("RU", "Russia");
    mapCoutriesName.put("RW", "Rwanda");
    mapCoutriesName.put("KN", "Saint Kitts and Nevis");
    mapCoutriesName.put("LC", "Saint Lucia");
    mapCoutriesName.put("PM", "Saint Pierre and Miquelon");
    mapCoutriesName.put("VC", "Saint Vincent and the Grenadines");
    mapCoutriesName.put("WS", "Samoa");
    mapCoutriesName.put("SM", "Sam Marino");
    mapCoutriesName.put("SA", "Saudi Arabia");
    mapCoutriesName.put("SN", "Senegal");
    mapCoutriesName.put("RS", "Serbia");
    mapCoutriesName.put("SC", "Seychelles");
    mapCoutriesName.put("SL", "Sierra Leone");
    mapCoutriesName.put("SG", "Singapore");
    mapCoutriesName.put("SK", "Slovakia");
    mapCoutriesName.put("SI", "Slovenia");
    mapCoutriesName.put("SO", "Somalia");
    mapCoutriesName.put("ZA", "South Africa");
    mapCoutriesName.put("KR", "South Korea");
    mapCoutriesName.put("ES", "Spain");
    mapCoutriesName.put("LK", "Sri Lanka");
    mapCoutriesName.put("SD", "Sudan");
    mapCoutriesName.put("SR", "Suriname");
    mapCoutriesName.put("SZ", "Swaziland");
    mapCoutriesName.put("SE", "Sweden");
    mapCoutriesName.put("CH", "Switzerland");
    mapCoutriesName.put("SY", "Syria");
    mapCoutriesName.put("TW", "Taiwan");
    mapCoutriesName.put("TJ", "Tajikistan");
    mapCoutriesName.put("TZ", "Tanzania");
    mapCoutriesName.put("TH", "Thailand");
    mapCoutriesName.put("TG", "Togo");
    mapCoutriesName.put("TO", "Tonga");
    mapCoutriesName.put("TT", "Trinidad and Tobago");
    mapCoutriesName.put("TN", "Tunisia");
    mapCoutriesName.put("TR", "Turkey");
    mapCoutriesName.put("TM", "Turkmenistan");
    mapCoutriesName.put("TC", "Turks and Caicos Islands");
    mapCoutriesName.put("TV", "Tuvalu");
    mapCoutriesName.put("VI", "U.S. Virgin Islands");
    mapCoutriesName.put("UG", "Uganda");
    mapCoutriesName.put("UA", "Ukraine");
    mapCoutriesName.put("AE", "United Arab Emirates");
    mapCoutriesName.put("GB", "United Kingdom");
    mapCoutriesName.put("US", "United States");
    mapCoutriesName.put("UY", "Uruguay");
    mapCoutriesName.put("UZ", "Uzbekistan");
    mapCoutriesName.put("VU", "Vanuatu");
    mapCoutriesName.put("VE", "Venezuela");
    mapCoutriesName.put("VN", "Vietnam");
    mapCoutriesName.put("YE", "Yemen");
    mapCoutriesName.put("ZM", "Zambia");
    mapCoutriesName.put("ZW", "Zimbabwe");
  }

  public HashMap<String, String> getMapCoutriesName() {
    return mapCoutriesName;
  }

  public void setMapCoutriesName(HashMap<String, String> mapCoutriesName) {
    this.mapCoutriesName = mapCoutriesName;
  }


}
