TRUNCATE TABLE PAYMENT_GATEWAY_CONFIG;
INSERT INTO PAYMENT_GATEWAY_CONFIG(CONFIGID, PAYMENTGATEWAYNAME, PAYMENTGATEWAYSTATUS, REVENUECENTERID, REVENUECENTERCODE, CONFIGURATIONNAME, CONFIGURATIONVALUE, PAYMENTMETHODCODE) VALUES (455, 'DummyGateway', 'On', null, null, null, null, 'MASTER');
