CREATE TABLE PRODUCT_LIVE
    (PRODUCTID                      NUMBER(10),
    PRODUCT_GROUP_ID               NUMBER(10),
    PRODUCTNAME                    VARCHAR2(255),
    PRODUCTCODE                    VARCHAR2(50),
    GLCODE                         VARCHAR2(50),
    DESCRIPTION                    VARCHAR2(500),
    REMARKS                        VARCHAR2(1000),
    KEYWORDSEARCH                  VARCHAR2(255),
    REPORTVISIBILITY               CHAR(1),
    FINANCIALREPORTVISIBILITY      CHAR(1),
    PRODUCTOWNER                   VARCHAR2(128),
    WEIGHT                         NUMBER(5),
    SALESSTATUS                    NUMBER(1),
    ACTIVATIONSTATUS               NUMBER(1),
    MAXTICKETSAPPL                 NUMBER(3),
    STARTDATE                      TIMESTAMP (0),
    ENDDATE                        TIMESTAMP (0),
    CREATED_BY                     NUMBER(10),
    CREATEDDATE                    TIMESTAMP (0) ,
    UPDATED_BY                     NUMBER(10),
    UPDATEDDATE                    TIMESTAMP (0),
    STOP_SALES_REASON_MCT_ID       NUMBER(10),
    FESTIVAL_CODE_ID               NUMBER(10),
    SPAN_CODE_MCT_ID               NUMBER(10),
    VENUE_ID                       NUMBER(10),
    VENUELAYOUTCONFIG_ID           NUMBER(10),
    SALESPIC                       NVARCHAR2(128),
    EVENTBUILDER                   NVARCHAR2(255))