spring:
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
      zipkin:
        discovery:
          enabled: false
      reload:
        enabled: false
  autoconfigure:
    exclude: io.fabric8.spring.cloud.discovery.KubernetesDiscoveryClientConfiguration
#  boot:
#    admin:
#      url: http://localhost:8761/admin/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
