truncate TABLE EVOUCHER_CREDIT_CARD_REGEX;

INSERT INTO EVOUCHER_CREDIT_CARD_REGEX(EVOUCHER_ID, CC_REGEX) VALUES('MCjT1X5GTU', '^545301\d{10}$');
INSERT INTO EVOUCHER_CREDIT_CARD_REGEX(EVOUCHER_ID, CC_REGEX) VALUES('MCjT1H5GTU', '^545301\d{10}$');
INSERT INTO EVOUCHER_CREDIT_CARD_REGEX(EVOUCHER_ID, CC_REGEX) VALUES('MCjT1O5GTU', '^545301\d{10}$');