truncate table EVOUCHER_VIEW;

ALTER TABLE EVOUCHER_VIEW
  ALTER COLUMN ORGANIZATION_ID SET NULL;
  
ALTER TABLE EVOUCHER_VIEW
  ALTER COLUMN PATRON_ID SET NULL;


-- basic expired
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCKrKE4VNu', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-08-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'REDEEM_RESTRICTIONS', 'RESTRICT_WITHIN', 7);
-- basic inactive
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MC6KakMUyB', 'SISTIC_E_VOUCHER', 20,0,TO_TIMESTAMP('2016-08-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'REDEEM_RESTRICTIONS', 'RESTRICT_WITHIN', 7);
-- redeemed
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCQc1rn30P', 'SISTIC_E_VOUCHER', 20,2,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'REDEEM_RESTRICTIONS', 'RESTRICT_WITHIN', 7);

-- invalid venue
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCjT1X5GTU', 'DBS_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'VENUE', '36', 7);

-- invalid organization
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCP5X2FX7F', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'ORGANIZATION', '548', 7);

-- invalid membership
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCqVqNwJ20', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,1364937,null, 'MEMBERSHIP_PATRON_ACCT_NO', 'MEMBERSHIP_PATRON_ACCT_NO', 7);

-- invalid usage with others
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCjSc6MEy8', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'USAGE_WITH_OTHER_VOUCHERS', 'FALSE', 7);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCHPSQW0TY', 'ESPLANADE_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'USAGE_WITH_OTHER_VOUCHERS', 'FALSE', 7);

-- invalid max qty
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCsYGurMpf', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'MAXIMUM_QTY', '1', 7);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCubXpR1pH', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'MAXIMUM_QTY', '1', 7);

-- invalid redeem restrictions within
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCsY35rM8f', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'REDEEM_RESTRICTIONS', 'RESTRICT_WITHIN', 7);

-- invalid redeem restrictions outside
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MC63XpR1p8', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'REDEEM_RESTRICTIONS', 'RESTRICT_OUTSIDE', 7);

-- invalid redeem restrictions all
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('Ck63XpR1p8', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'REDEEM_RESTRICTIONS', 'RESTRICT_ALL', 7);

-- valid redeem restrictions none
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('Nk63XpR1p8', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'REDEEM_RESTRICTIONS', 'RESTRICT_NONE', 7);

-- payment method
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('Pl63NpR1p3', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'PAYMENT_METHOD', 'MASTERCARD;', 7);

-- credit card
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('CmW3NpR1p3', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'CREDIT_CARD', '5;', 7);

-- multi rules - first rule failed
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('BmW3NpR1p3', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'ORGANIZATION', '548', 2);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('BmW3NpR1p3', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'VENUE', '3850', 3);

-- multi rules - last rule failed
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('BmK8NpPw3', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'ORGANIZATION', '547', 2);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('BmK8NpPw3', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'VENUE', '3851', 3);

-- multi rules - pass all rules
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('Bm98NpEd1', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'ORGANIZATION', '547', 2);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('Bm98NpEd1', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'VENUE', '3850', 3);

-- multi e-vouchers - first e-voucher failed
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('Hi98NpEd1', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'ORGANIZATION', '548', 2);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('Kc35NpEd1', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'VENUE', '3850', 3);

-- multi e-vouchers - last e-voucher failed
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('FPi98NpEd1', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'ORGANIZATION', '547', 2);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('LF35NpEd1', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'VENUE', '3851', 3);

-- multi e-vouchers - all failed
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('FFi98NpEd2', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'ORGANIZATION', '548', 2);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('LF35NpEd2', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'VENUE', '3851', 3);

-- multi e-vouchers - all pass
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('FPi98NpEd2', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'ORGANIZATION', '547', 2);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('LP35NpEd2', 'SISTIC_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'VENUE', '3850', 3);

-- dbs failed
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCjT1X5GTU', 'DBS_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'VENUE', '56', 2);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCjT1X5GTU', 'DBS_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'REDEEM_RESTRICTIONS', 'RESTRICT_WITHIN', 7);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCjT1X5GTU', 'DBS_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'MAXIMUM_QTY', '1', 4);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCjT1X5GTU', 'DBS_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'USAGE_WITH_OTHER_VOUCHERS', 'FALSE', 3);
INSERT INTO EVOUCHER_VIEW (E_VOUCHER_ID, E_VOUCHER_TYPE, REDEEM_VALUE, E_VOUCHER_STATUS, START_DATE, END_DATE, ORGANIZATION_ID, PATRON_ID, IS_GIFT_VOUCHER, ATTRIBUTE_NAME, ATTRIBUTE_VALUE, PRIORITY) VALUES ('MCjT1X5GTU', 'DBS_E_VOUCHER', 20,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2017-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),null,null,null, 'ORGANIZATION', '547', 1);
