create table PRDT_MAPPING_CONFIG(
	PRDT_MAPPING_CONFIGID NUMBER(10),
	INTERNAL_PRODT_ID NUMBER(10),
	EXTERNAL_PRODT_ID NUMBER(10)
);

INSERT INTO PRDT_MAPPING_CONFIG (PRDT_MAPPING_CONFIGID,INTERNAL_PRODT_ID,EXTERNAL_PRODT_ID) 
VALUES(1,105296,70501);
INSERT INTO PRDT_MAPPING_CONFIG (PRDT_MAPPING_CONFIGID,INTERNAL_PRODT_ID,EXTERNAL_PRODT_ID) 
VALUES(2,122000,70502);
