TRUNCATE TABLE detail_seatmap;
INSERT INTO DETAIL_SEATMAP (PRODUCT_ID, PRICE_CAT_ID, SECTION_ID, IMAGE_AVAILABLE, VIEW_FROM_SEAT_AVAILABLE, SEAT_MAPPING_ID, DETAIL_IMAGE, SECTION_ALIAS, INTERACTIVE, RANK, SEAT_SALES_STATUS, INVENTORY_ID, SEAT_ROW_ALIAS, SEAT_ALIAS, SEAT_TYPE, COORDINATES, TOP_LEFT_COORDINATES, SEAT_ANGLE, SEAT_SECTION_ALIAS, PROFILE_INFO_ID)
VALUES
  (243851, 18284, 356153, 0, 0, NULL, NULL, 'Stall', 0, 3, 0, 120943553, 'PA', '8', 1, NULL, NULL,
   NULL, 'Stall', 11);
