TRUNCATE TABLE PRICE_TABLE_INFO;

ALTER TABLE price_table_info
  ADD promotion_password_id NUMBER(10);

INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D5', 'Group Booking 30%', 'Cat 3', 3, 52.50000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D2', '20% NSF', 'Cat 1', 1, 76.00000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D1', '25% Senior Citizen', 'Cat 1', 1, 71.25000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D', '25% Student', 'Cat 3', 3, 56.25000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'A', 'Standard', 'Cat 3', 3, 75.00000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D5', 'Group Booking 30%', 'Cat 2', 2, 59.50000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D2', '20% NSF', 'Cat 2', 2, 68.00000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D1', '25% Senior Citizen', 'Cat 3', 3, 56.25000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D', '25% Student', 'Cat 2', 2, 63.75000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'A', 'Standard', 'Cat 1', 1, 95.00000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D5', 'Group Booking 30%', 'Cat 1', 1, 66.50000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D', '25% Student', 'Cat 1', 1, 71.25000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D1', '25% Senior Citizen', 'Cat 2', 2, 63.75000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'A', 'Standard', 'Cat 2', 2, 85.00000, 19, NULL, 18332);
INSERT INTO PRICE_TABLE_INFO (PRODUCTID, PROFILE_INFO_ID, PRICECLASSCODE, PRICECLASSNAME, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRICEVALUE, PRICE_STATUS, promotion_password_id, PRICE_CATEGORY_ID)
VALUES (243851, 11, 'D2', '20% NSF', 'Cat 3', 3, 60.00000, 19, NULL, 18332);
