TRUNCATE TABLE SEATMAP_AVAILABLITY_PRODUCTS;

ALTER TABLE SEATMAP_AVAILABLITY_PRODUCTS
  ADD promotion_password_id NUMBER(10);

INSERT INTO SEATMAP_AVAILABLITY_PRODUCTS (PRODUCTID, SEATSECTIONID, PRICE_CAT_ID, PROFILE_INFO_ID, SEAT_SECTION_AVAILABILITY, PROMOTION_PASSWORD_ID)
VALUES (243851, 356151, 18286, 11, 1, NULL);
INSERT INTO SEATMAP_AVAILABLITY_PRODUCTS (PRODUCTID, SEATSECTIONID, PRICE_CAT_ID, PROFILE_INFO_ID, SEAT_SECTION_AVAILABILITY, PROMOTION_PASSWORD_ID)
VALUES (243851, 356152, 18285, 11, 1, NULL);
INSERT INTO SEATMAP_AVAILABLITY_PRODUCTS (PRODUCTID, SEATSECTIONID, PRICE_CAT_ID, PROFILE_INFO_ID, SEAT_SECTION_AVAILABILITY, PROMOTION_PASSWORD_ID)
VALUES (243851, 356153, 18284, 11, 1, NULL);
