TRUNCATE TABLE MASTER_CODE_TABLE;

INSERT INTO MASTER_CODE_TABLE (MASTERCODEID,CATEGORYCODE,STATUS,DESCRIPTION1,DESCRIPTION2) VALUES (576,'Transaction Type', 1, 'Resend', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID,CATEGORYCODE,STATUS,DESCRIPTION1,DESCRIPTION2) VALUES (628,'Transaction Type', 1, 'Reset', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID,CATEGORYCODE,STATUS,DESCRIPTION1,DESCRIPTION2) VALUES (642,'Transaction Type', 1, 'Delivery Method Change', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID,CATEGORYCODE,STATUS,DESCRIPTION1,DESCRIPTION2) VALUES (11,'Transaction Type', 1, 'Purchase', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID,CATEGORYCODE,STATUS,DESCRIPTION1,DESCRIPTION2) VALUES (12,'Transaction Type', 1, 'Return', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID,CATEGORYCODE,STATUS,DESCRIPTION1,DESCRIPTION2) VALUES (13,'Transaction Type', 1, 'Replace', null);