truncate TABLE patron_solicitation;
truncate TABLE Organization;
truncate TABLE Patron_Profile;
truncate TABLE Product_Live;
truncate TABLE product_group_live;
truncate TABLE PRDT_GROUP_PROMOTER_LIVE;
truncate TABLE venue;
truncate TABLE location;

INSERT INTO patron_solicitation(patronsolicitationid, patron_profile_id, solicitation_type_mct_id, solicitation_label_mct_id, organization_id, subscriptionstatus, updateddate, updated_by) 
VALUES(961,1569068,200,NULL,142,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1209);
INSERT INTO patron_solicitation(patronsolicitationid, patron_profile_id, solicitation_type_mct_id, solicitation_label_mct_id, organization_id, subscriptionstatus, updateddate, updated_by) 
VALUES(962,1569068,200,NULL,1,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1209);
INSERT INTO patron_solicitation(patronsolicitationid, patron_profile_id, solicitation_type_mct_id, solicitation_label_mct_id, organization_id, subscriptionstatus, updateddate, updated_by) 
VALUES(963,1569068,201,NULL,1243,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1209);
INSERT INTO patron_solicitation(patronsolicitationid, patron_profile_id, solicitation_type_mct_id, solicitation_label_mct_id, organization_id, subscriptionstatus, updateddate, updated_by) 
VALUES(964,1569069,202,654,746,0,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1209);
--INSERT INTO patron_solicitation(patronsolicitationid, patron_profile_id, solicitation_type_mct_id, solicitation_label_mct_id, organization_id, subscriptionstatus, updateddate, updated_by) 
--VALUES(965,1569068,202,654,747,1,TO_TIMESTAMP('2016-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1209);

INSERT INTO Organization (ORGANIZATIONID,ORGANIZATIONNAME,REGISTRATIONNO,ISTENANT,KEYALIAS,ENCRYPTIONALGORITHM,ORGANIZATIONURL,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY) 
VALUES(142,'Gevorg Sargsyan',NULL,'F',NULL,NULL,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,NULL,NULL);
INSERT INTO Organization (ORGANIZATIONID,ORGANIZATIONNAME,REGISTRATIONNO,ISTENANT,KEYALIAS,ENCRYPTIONALGORITHM,ORGANIZATIONURL,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY) 
VALUES(1243,'Reitoku Kai',NULL,'F',NULL,NULL,'http://abcd.com',TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,NULL,NULL);
INSERT INTO Organization (ORGANIZATIONID,ORGANIZATIONNAME,REGISTRATIONNO,ISTENANT,KEYALIAS,ENCRYPTIONALGORITHM,ORGANIZATIONURL,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY) 
VALUES(750,'Amadeus Choral Society',NULL,'F',NULL,NULL,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,NULL,NULL);
INSERT INTO Organization (ORGANIZATIONID,ORGANIZATIONNAME,REGISTRATIONNO,ISTENANT,KEYALIAS,ENCRYPTIONALGORITHM,ORGANIZATIONURL,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY) 
VALUES(710,'AEGThemeSTAR',NULL,'F',NULL,NULL,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,NULL,NULL);
INSERT INTO Organization (ORGANIZATIONID,ORGANIZATIONNAME,REGISTRATIONNO,ISTENANT,KEYALIAS,ENCRYPTIONALGORITHM,ORGANIZATIONURL,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY) 
VALUES(746,'Jade Group Intl. Pte. Ltd.','200722795D','T',NULL,NULL,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,NULL,NULL);
--INSERT INTO Organization (ORGANIZATIONID,ORGANIZATIONNAME,REGISTRATIONNO,ISTENANT,KEYALIAS,ENCRYPTIONALGORITHM,ORGANIZATIONURL,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY) 
--VALUES(747,'Amadeus Intl. Pte. Ltd.','200722795D','F',NULL,NULL,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,NULL,NULL);


INSERT INTO patron_profile (PATRONPROFILEID,IDENTITYNO,ACCNO,STATUS,FIRSTNAME,LASTNAME,EMAILADDRESS,ISRECEIVETICKETINGAGENT,ISRECEIVEPROMOTER,ISRECEIVEVENUE,ISBILLINGADDRESSSAMEASMAILING,ISDONOTSIGNUP,ORGANIZATIONNAME,COMPANYID,COMPANYNAME,EMPLOYEEID,GUESTOF,EXTERNALID,ACCTREMARK,ACC_TYPE_MCT_ID,GENDER_MCT_ID,TITLE_MCT_ID,NATIONALITY,COUNTRYOFRESIDENCE,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY,IDENTITY_NO_TYPE_MCT_ID) 
VALUES(1569068,NULL,5000001,1,'DEVSISTIC','PATRON',NULL,'T','T','T','T','F',NULL,NULL,NULL,NULL,NULL,NULL,NULL,90,249,228,'KY','BS',TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),59,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),59,647);
INSERT INTO patron_profile (PATRONPROFILEID,IDENTITYNO,ACCNO,STATUS,FIRSTNAME,LASTNAME,EMAILADDRESS,ISRECEIVETICKETINGAGENT,ISRECEIVEPROMOTER,ISRECEIVEVENUE,ISBILLINGADDRESSSAMEASMAILING,ISDONOTSIGNUP,ORGANIZATIONNAME,COMPANYID,COMPANYNAME,EMPLOYEEID,GUESTOF,EXTERNALID,ACCTREMARK,ACC_TYPE_MCT_ID,GENDER_MCT_ID,TITLE_MCT_ID,NATIONALITY,COUNTRYOFRESIDENCE,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY,IDENTITY_NO_TYPE_MCT_ID) 
VALUES(2,NULL,5000002,1,'DEVSISTIC','PATRON',NULL,'F','F','F','F','T',NULL,NULL,NULL,NULL,NULL,NULL,NULL,90,249,228,'SG','SG',TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1210,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),59,648);
INSERT INTO patron_profile (PATRONPROFILEID,IDENTITYNO,ACCNO,STATUS,FIRSTNAME,LASTNAME,EMAILADDRESS,ISRECEIVETICKETINGAGENT,ISRECEIVEPROMOTER,ISRECEIVEVENUE,ISBILLINGADDRESSSAMEASMAILING,ISDONOTSIGNUP,ORGANIZATIONNAME,COMPANYID,COMPANYNAME,EMPLOYEEID,GUESTOF,EXTERNALID,ACCTREMARK,ACC_TYPE_MCT_ID,GENDER_MCT_ID,TITLE_MCT_ID,NATIONALITY,COUNTRYOFRESIDENCE,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY,IDENTITY_NO_TYPE_MCT_ID) 
VALUES(459,NULL,590868,1,'DEVSISTIC','PATRON',NULL,'T','T','T','F','F',NULL,NULL,NULL,NULL,NULL,NULL,NULL,90,250,NULL,'SG','SG',TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,648);
INSERT INTO patron_profile (PATRONPROFILEID,IDENTITYNO,ACCNO,STATUS,FIRSTNAME,LASTNAME,EMAILADDRESS,ISRECEIVETICKETINGAGENT,ISRECEIVEPROMOTER,ISRECEIVEVENUE,ISBILLINGADDRESSSAMEASMAILING,ISDONOTSIGNUP,ORGANIZATIONNAME,COMPANYID,COMPANYNAME,EMPLOYEEID,GUESTOF,EXTERNALID,ACCTREMARK,ACC_TYPE_MCT_ID,GENDER_MCT_ID,TITLE_MCT_ID,NATIONALITY,COUNTRYOFRESIDENCE,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY,IDENTITY_NO_TYPE_MCT_ID) 
VALUES(460,NULL,590864,1,'DEVSISTIC','PATRON',NULL,'F','F','F','F','F',NULL,NULL,NULL,NULL,NULL,NULL,NULL,90,NULL,NULL,'SG','SG',TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1209,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1209,646);
INSERT INTO patron_profile (PATRONPROFILEID,IDENTITYNO,ACCNO,STATUS,FIRSTNAME,LASTNAME,EMAILADDRESS,ISRECEIVETICKETINGAGENT,ISRECEIVEPROMOTER,ISRECEIVEVENUE,ISBILLINGADDRESSSAMEASMAILING,ISDONOTSIGNUP,ORGANIZATIONNAME,COMPANYID,COMPANYNAME,EMPLOYEEID,GUESTOF,EXTERNALID,ACCTREMARK,ACC_TYPE_MCT_ID,GENDER_MCT_ID,TITLE_MCT_ID,NATIONALITY,COUNTRYOFRESIDENCE,CREATEDDATE,CREATED_BY,UPDATEDDATE,UPDATED_BY,IDENTITY_NO_TYPE_MCT_ID) 
VALUES(461,NULL,590834,1,'DEVSISTIC','PATRON',NULL,'T','F','F','F','F',NULL,NULL,NULL,NULL,NULL,NULL,NULL,90,NULL,NULL,'SG','SG',TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1,648);

INSERT INTO product_live (PRODUCTID,PRODUCT_GROUP_ID,PRODUCTNAME,PRODUCTCODE,GLCODE,DESCRIPTION,REMARKS,KEYWORDSEARCH,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,WEIGHT,SALESSTATUS,ACTIVATIONSTATUS,MAXTICKETSAPPL,STARTDATE,ENDDATE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,STOP_SALES_REASON_MCT_ID,FESTIVAL_CODE_ID,SPAN_CODE_MCT_ID,VENUE_ID,VENUELAYOUTCONFIG_ID,SALESPIC,EVENTBUILDER) 
VALUES(3,1,'LOLA (PG) (Test)','eaft1311222000','french1013',NULL,NULL,'French Movie 2013','T','T','Melody Tang',NULL,1,1,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),14,NULL,NULL,50,151,NULL,NULL);
INSERT INTO product_live (PRODUCTID,PRODUCT_GROUP_ID,PRODUCTNAME,PRODUCTCODE,GLCODE,DESCRIPTION,REMARKS,KEYWORDSEARCH,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,WEIGHT,SALESSTATUS,ACTIVATIONSTATUS,MAXTICKETSAPPL,STARTDATE,ENDDATE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,STOP_SALES_REASON_MCT_ID,FESTIVAL_CODE_ID,SPAN_CODE_MCT_ID,VENUE_ID,VENUELAYOUTCONFIG_ID,SALESPIC,EVENTBUILDER) 
VALUES(2,1,'LOLA (PG) (Test)','eaft1312222000','french1013',NULL,NULL,'French Movie 2013','T','T','Melody Tang',NULL,1,1,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),14,NULL,NULL,50,150,NULL,NULL);
INSERT INTO product_live (PRODUCTID,PRODUCT_GROUP_ID,PRODUCTNAME,PRODUCTCODE,GLCODE,DESCRIPTION,REMARKS,KEYWORDSEARCH,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,WEIGHT,SALESSTATUS,ACTIVATIONSTATUS,MAXTICKETSAPPL,STARTDATE,ENDDATE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,STOP_SALES_REASON_MCT_ID,FESTIVAL_CODE_ID,SPAN_CODE_MCT_ID,VENUE_ID,VENUELAYOUTCONFIG_ID,SALESPIC,EVENTBUILDER) 
VALUES(16,1,'LOLA (PG) (Test)','eaft1310222000','french1013',NULL,NULL,'French Movie 2013','T','T','Melody Tang',NULL,0,1,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,NULL,251,200,NULL,NULL);
INSERT INTO product_live (PRODUCTID,PRODUCT_GROUP_ID,PRODUCTNAME,PRODUCTCODE,GLCODE,DESCRIPTION,REMARKS,KEYWORDSEARCH,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,WEIGHT,SALESSTATUS,ACTIVATIONSTATUS,MAXTICKETSAPPL,STARTDATE,ENDDATE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,STOP_SALES_REASON_MCT_ID,FESTIVAL_CODE_ID,SPAN_CODE_MCT_ID,VENUE_ID,VENUELAYOUTCONFIG_ID,SALESPIC,EVENTBUILDER) 
VALUES(161,49,'TOREO (PG) (Test)','eaft1311092000','spain1113',NULL,NULL,'Spanish Movie Fiesta 2013 (Test)','T','T','allison',NULL,0,1,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,NULL,151,1150,NULL,NULL);
INSERT INTO product_live (PRODUCTID,PRODUCT_GROUP_ID,PRODUCTNAME,PRODUCTCODE,GLCODE,DESCRIPTION,REMARKS,KEYWORDSEARCH,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,WEIGHT,SALESSTATUS,ACTIVATIONSTATUS,MAXTICKETSAPPL,STARTDATE,ENDDATE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,STOP_SALES_REASON_MCT_ID,FESTIVAL_CODE_ID,SPAN_CODE_MCT_ID,VENUE_ID,VENUELAYOUTCONFIG_ID,SALESPIC,EVENTBUILDER) 
VALUES(162,49,'TOREO (PG) (Test)','eaft1311102000','spain1113',NULL,NULL,'Spanish Movie Fiesta 2013 (Test)','T','T','allison',NULL,0,1,NULL,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,NULL,50,1200,NULL,NULL);

INSERT INTO product_group_live (PRODUCTGROUPID,PRODUCTGROUPNAME,PRODUCTGROUPCODE,GLCODE,DESCRIPTION,REMARKS,ISTAXINCLUSIVE,TAX_PERCENT_ID,KEYWORDSEARCH,PORTALURL,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,INTERNETCONTENTCODE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,WEIGHT,FESTIVAL_CODE_ID,CATEGORY_CODE_MCT_ID,SPAN_CODE_MCT_ID,SALESPIC,EVENTBUILDER) 
VALUES(1,'FRENCH MOVIES 2013 (Test)','french1013','french1013',NULL,NULL,'T',1,'French Movie 2013',NULL,'T','T','Melody Tang','french1013',28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,26,NULL,NULL,NULL);
INSERT INTO product_group_live (PRODUCTGROUPID,PRODUCTGROUPNAME,PRODUCTGROUPCODE,GLCODE,DESCRIPTION,REMARKS,ISTAXINCLUSIVE,TAX_PERCENT_ID,KEYWORDSEARCH,PORTALURL,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,INTERNETCONTENTCODE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,WEIGHT,FESTIVAL_CODE_ID,CATEGORY_CODE_MCT_ID,SPAN_CODE_MCT_ID,SALESPIC,EVENTBUILDER) 
VALUES(49,'Spanish Movie Fiesta 2013 (Test)','spain1113','spain1113',NULL,NULL,'T',1,'Spanish Movie Fiesta 2013 (Test)','http://192.168.10.238/events/spain1113','T','T','allison','spain1113',30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,26,NULL,NULL,NULL);
INSERT INTO product_group_live (PRODUCTGROUPID,PRODUCTGROUPNAME,PRODUCTGROUPCODE,GLCODE,DESCRIPTION,REMARKS,ISTAXINCLUSIVE,TAX_PERCENT_ID,KEYWORDSEARCH,PORTALURL,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,INTERNETCONTENTCODE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,WEIGHT,FESTIVAL_CODE_ID,CATEGORY_CODE_MCT_ID,SPAN_CODE_MCT_ID,SALESPIC,EVENTBUILDER) 
VALUES(13,'Singapore Marvel Film Festival (Aksaas Test)','smff2013','smff2013','Test1',NULL,'T',1,'Singapore Marvel Film Festival (Aksaas Test)',NULL,'T','T','dannytan','smff2013',30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,26,NULL,NULL,NULL);
INSERT INTO product_group_live (PRODUCTGROUPID,PRODUCTGROUPNAME,PRODUCTGROUPCODE,GLCODE,DESCRIPTION,REMARKS,ISTAXINCLUSIVE,TAX_PERCENT_ID,KEYWORDSEARCH,PORTALURL,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,INTERNETCONTENTCODE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,WEIGHT,FESTIVAL_CODE_ID,CATEGORY_CODE_MCT_ID,SPAN_CODE_MCT_ID,SALESPIC,EVENTBUILDER) 
VALUES(79,'Poprocks Live In Concert (Test)','pop1213','pop1213',NULL,NULL,'T',1,'Poprocks Live In Concert (Test)',NULL,'T','T','allison','pop1213',30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,26,NULL,NULL,NULL);
INSERT INTO product_group_live (PRODUCTGROUPID,PRODUCTGROUPNAME,PRODUCTGROUPCODE,GLCODE,DESCRIPTION,REMARKS,ISTAXINCLUSIVE,TAX_PERCENT_ID,KEYWORDSEARCH,PORTALURL,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,INTERNETCONTENTCODE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,WEIGHT,FESTIVAL_CODE_ID,CATEGORY_CODE_MCT_ID,SPAN_CODE_MCT_ID,SALESPIC,EVENTBUILDER) 
VALUES(83,'A Spanish Tenor In Concert (Test)','tenor2013','tenor2013',NULL,NULL,'T',1,'A Spanish Tenor In Concert (Test)',NULL,'T','T','allison','tenor1213',28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),28,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,26,30,NULL,NULL);

INSERT INTO PRDT_GROUP_PROMOTER_LIVE (PRDTGRPPROMOTERID,PRDT_GRP_ID,PROMOTER_ID,PROMOTERGLCODE) 
VALUES(44,1,750,NULL);
INSERT INTO PRDT_GROUP_PROMOTER_LIVE (PRDTGRPPROMOTERID,PRDT_GRP_ID,PROMOTER_ID,PROMOTERGLCODE) 
VALUES(64,13,107,NULL);
INSERT INTO PRDT_GROUP_PROMOTER_LIVE (PRDTGRPPROMOTERID,PRDT_GRP_ID,PROMOTER_ID,PROMOTERGLCODE) 
VALUES(48,19,1470,NULL);
INSERT INTO PRDT_GROUP_PROMOTER_LIVE (PRDTGRPPROMOTERID,PRDT_GRP_ID,PROMOTER_ID,PROMOTERGLCODE) 
VALUES(61,49,1243,NULL);
INSERT INTO PRDT_GROUP_PROMOTER_LIVE (PRDTGRPPROMOTERID,PRDT_GRP_ID,PROMOTER_ID,PROMOTERGLCODE) 
VALUES(92,79,1464,NULL);

INSERT INTO venue (VENUEID,LOCATION_ID,VENUENAME,VENUEALIAS,VENUECAPACITY,REMARKS,UPDATED_BY,UPDATEDDATE,CREATEDDATE,CREATED_BY,STATUS,VENUEURL) 
VALUES(50,100,'The MAX Pavilion @ Singapore EXPO','The MAX Pavilion @ Singapore EXPO',5000,NULL,31,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,1,'http://singaporeexpo.com.sg/?s=max+pavilion');
INSERT INTO venue (VENUEID,LOCATION_ID,VENUENAME,VENUEALIAS,VENUECAPACITY,REMARKS,UPDATED_BY,UPDATEDDATE,CREATEDDATE,CREATED_BY,STATUS,VENUEURL) 
VALUES(151,151,'The Meadow, Gardens By The Bay','The Meadow, Gardens By The Bay',30000,NULL,30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,1,'http://www.gardensbythebay.com.sg/content/gbb/en/events-venues/meadow.html');
INSERT INTO venue (VENUEID,LOCATION_ID,VENUENAME,VENUEALIAS,VENUECAPACITY,REMARKS,UPDATED_BY,UPDATEDDATE,CREATEDDATE,CREATED_BY,STATUS,VENUEURL) 
VALUES(251,250,'The Star Theatre, The Star Performing Arts Centre','The Star Theatre, The Star Performing Arts Centre',5118,NULL,30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),83,1,'http://thestar.sg/the-star-theatre');
INSERT INTO venue (VENUEID,LOCATION_ID,VENUENAME,VENUEALIAS,VENUECAPACITY,REMARKS,UPDATED_BY,UPDATEDDATE,CREATEDDATE,CREATED_BY,STATUS,VENUEURL) 
VALUES(350,350,'SOTA Drama Theatre','SOTA Drama Theatre',418,NULL,86,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),86,1,'http://www.sota.edu.sg/VenueRental/SOTAPerformingArtsVenues/DramaTheatre.aspx');
INSERT INTO venue (VENUEID,LOCATION_ID,VENUENAME,VENUEALIAS,VENUECAPACITY,REMARKS,UPDATED_BY,UPDATEDDATE,CREATEDDATE,CREATED_BY,STATUS,VENUEURL) 
VALUES(550,51,'Esplanade Theatre Studio','Esplanade Theatre Studio',220,NULL,80,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),80,1,'http://www.esplanade.com/index.jsp');

INSERT INTO location (LOCATIONID,ORGANIZATION_ID,LOCATIONNAME,PRINTABLELOCATIONNAME,DISPLAYALIAS,ADDRESS,REMARKS,LOCATIONALIAS,MAILADDRESS,STATUS,UPDATEDDATE,UPDATED_BY,CREATEDDATE,CREATED_BY,LATITUDE,LONGITUDE) 
VALUES(100,710,'Singapore EXPO Convention and Exhibition Centre','Singapore EXPO Convention and Exhibition Centre',NULL,'1 Expo Drive, #02-01. Singapore 486150.','Multiple Venue:-
EXPO Hall 1 to 9
The Max Pavilion',NULL,'1 Expo Drive, #02-01. Singapore 486150.','1',TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,NULL,NULL,1.332875,103.95901);
INSERT INTO location (LOCATIONID,ORGANIZATION_ID,LOCATIONNAME,PRINTABLELOCATIONNAME,DISPLAYALIAS,ADDRESS,REMARKS,LOCATIONALIAS,MAILADDRESS,STATUS,UPDATEDDATE,UPDATED_BY,CREATEDDATE,CREATED_BY,LATITUDE,LONGITUDE) 
VALUES(151,142,'Gardens By The Bay','Gardens By The Bay',NULL,'18 Marina Gardens Drive Singapore 018953',NULL,NULL,'18 Marina Gardens Drive Singapore 018953','1',TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),30,1.278728,103.86492);
INSERT INTO location (LOCATIONID,ORGANIZATION_ID,LOCATIONNAME,PRINTABLELOCATIONNAME,DISPLAYALIAS,ADDRESS,REMARKS,LOCATIONALIAS,MAILADDRESS,STATUS,UPDATEDDATE,UPDATED_BY,CREATEDDATE,CREATED_BY,LATITUDE,LONGITUDE) 
VALUES(350,1467,'School of The Arts Singapore','School of The Arts Singapore',NULL,'227968',NULL,NULL,'1 Zubir Said Drive
Singapore 227968','1',TO_TIMESTAMP('2013-10-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),86,NULL,NULL,1.298907,103.84871);


