TRUNCATE TABLE sales_seat_inventory;
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555775, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555776, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555777, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555778, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555779, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555780, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555781, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555782, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555783, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555784, 245634, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, systimestamp,
                                                                    1437, NULL, NULL, 0, NULL,
                                                                    NULL, 356882, NULL, NULL,
   NULL, NULL, NULL, NULL);