truncate table SALES_SEAT_INVENTORY;
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553775, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 18:20:35',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553776, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 18:14:31',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553777, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 18:14:31',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553778, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 18:14:31',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553779, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 18:14:31',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553780, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 18:14:31',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553781, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 18:14:31',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553782, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 18:14:31',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553783, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 18:14:31',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES (121553784, 245632, 0, 0, 1, 12176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                                                         TO_TIMESTAMP(
                                                                             '2016-10-06 17:29:51',
                                                                             'YYYY-MM-DD HH24:MI:SS'),
                                                                         1437, NULL, NULL, 0, NULL,
                                                                         NULL, 356880, NULL, NULL,
        NULL, NULL, NULL, NULL);


truncate TABLE PRICE_MODEL_TPL_PRDT_LIVE;
INSERT INTO PRICE_MODEL_TPL_PRDT_LIVE (PRICEMODELTPLPRDTID, PRICE_MODEL_TEMPLATE_ID, PRODUCT_ID, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY)
VALUES (163643, 13832, 245632, TO_TIMESTAMP('2017-01-03 12:21:07', 'YYYY-MM-DD HH24:MI:SS'), 1031, TO_TIMESTAMP('2017-01-03 12:21:07', 'YYYY-MM-DD HH24:MI:SS'), 1031);

truncate TABLE PMT_ROW_LIVE;
INSERT INTO PMT_ROW_LIVE (PMTROWID, TICKETPRINTALIAS, ISDISPLAYFORSALES, ISSTANDARD, RANKING, QUOTA, PRICECLASS_ID, PRICEMODELTEMPLATE_ID, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY)
VALUES (141571, null, 'T', 'T', 3, 0, 75586, 13832, TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031, TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031);

truncate TABLE PRICE_CLASS_LIVE;
INSERT INTO PRICE_CLASS_LIVE (PRICECLASSID, PRICECLASSNAME, PRICECLASSCODE, PRICECLASSDESCRIPTION, ISCOMPLIMENTARYTICKET, ISPACKAGECLASS, DISCOUNTRULE, PRICEVALUERULE, SPANQUOTA, BUYTICKETSQUANTITY, GETTICKETQUANTITY, OFFVALUE, PVPRICECLASS_ID, DISCOUNTPRICECLASS_ID, TYPEOFDISCOUNT_MCT_ID, PROMOTIONPASSWORD_ID, CREDITCARDRANGE_ID, PRODUCTGROUP_ID, VALIDITY_PERIOD, CHANNELS, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY, ORDERING)
VALUES (75586, 'Standard Adult', 'A', 'Standard Adult', 'F', 'F', 1, 1, 0, 0, 0, 0.00000, null, null, null, null, null, 16017, null, 'All Channel', TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031, TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031, 8);