--All Delivery Method Related
TRUNCATE TABLE DELIVERY_METHOD;
TRUNCATE TABLE DELIVERY_TPL_DETAIL_LIVE;
TRUNCATE TABLE DELIVERY_METHOD_TEMPLATE_LIVE;
TRUNCATE TABLE DELIVERY_TPL_PRDT_LIVE;
TRUNCATE TABLE PROFILE_DELIVERY_METHOD;


INSERT INTO DELIVERY_METHOD (DELIVERYMETHODID, ADDRESSREQUIRED, DELIVERYMETHODNAME, DELIVERYTYPE, DESCRIPTION, EMAILREQUIRED, MOBILENOREQUIRED, ORDERMETHOD, DELIVERYMETHODCODE, TICKETTYPE) VALUES (52, 1, 'Registered Mail', 'RM', 'Registered Mail', 0, 0, 3, 'REGISTERED_MAIL', 1);
INSERT INTO DELIVERY_METHOD (DELIVERYMETHODID, ADDRESSREQUIRED, DELIVERYMETHODNAME, DELIVERYTYPE, DESCRIPTION, EMAILREQUIRED, MOBILENOREQUIRED, ORDERMETHOD, DELIVERYMETHODCODE, TICKETTYPE) VALUES (60, 1, 'Registered Mail - Payment by World & World Elite MasterCard', 'RM', 'Registered Mail - Payment by World & World Elite MasterCard', 0, 0, 1, 'MAIL_WORLD_ELITE_MASTERCARD', 1);
INSERT INTO DELIVERY_METHOD (DELIVERYMETHODID, ADDRESSREQUIRED, DELIVERYMETHODNAME, DELIVERYTYPE, DESCRIPTION, EMAILREQUIRED, MOBILENOREQUIRED, ORDERMETHOD, DELIVERYMETHODCODE, TICKETTYPE) VALUES (40, 0, 'Pickup waived for MasterCard holder', 'OP', 'Pickup waived for MasterCard holder', 0, 0, 6, 'MASTERCARD_PICKUP', 1);
INSERT INTO DELIVERY_METHOD (DELIVERYMETHODID, ADDRESSREQUIRED, DELIVERYMETHODNAME, DELIVERYTYPE, DESCRIPTION, EMAILREQUIRED, MOBILENOREQUIRED, ORDERMETHOD, DELIVERYMETHODCODE, TICKETTYPE) VALUES (1, 1, 'Courier', 'C', 'Courier', 0, 0, 4, 'COURIER', 1);
INSERT INTO DELIVERY_METHOD (DELIVERYMETHODID, ADDRESSREQUIRED, DELIVERYMETHODNAME, DELIVERYTYPE, DESCRIPTION, EMAILREQUIRED, MOBILENOREQUIRED, ORDERMETHOD, DELIVERYMETHODCODE, TICKETTYPE) VALUES (47, 0, 'Collection from Singapore Authorised Agents', 'OP', 'Collection from Singapore Authorised Agents', 0, 0, 0, 'OUTLET_PICKUP', 1);
INSERT INTO DELIVERY_METHOD (DELIVERYMETHODID, ADDRESSREQUIRED, DELIVERYMETHODNAME, DELIVERYTYPE, DESCRIPTION, EMAILREQUIRED, MOBILENOREQUIRED, ORDERMETHOD, DELIVERYMETHODCODE, TICKETTYPE) VALUES (45, 0, 'No Tickets Issued', 'Normal', 'No Tickets Issued', 0, 0, 8, 'NO_TICKETS_ISSUED', 1);
INSERT INTO DELIVERY_METHOD (DELIVERYMETHODID, ADDRESSREQUIRED, DELIVERYMETHODNAME, DELIVERYTYPE, DESCRIPTION, EMAILREQUIRED, MOBILENOREQUIRED, ORDERMETHOD, DELIVERYMETHODCODE, TICKETTYPE) VALUES (3, 0, 'E-ticket', 'Email', 'E-ticket', 1, 0, 7, 'E_TICKET', 2);
INSERT INTO DELIVERY_METHOD (DELIVERYMETHODID, ADDRESSREQUIRED, DELIVERYMETHODNAME, DELIVERYTYPE, DESCRIPTION, EMAILREQUIRED, MOBILENOREQUIRED, ORDERMETHOD, DELIVERYMETHODCODE, TICKETTYPE) VALUES (98, 0, 'Collection from Singapore Authorised Agents (Overseas Agent)', 'OP', 'Collection from Singapore Authorised Agents (Overseas Agent)', 0, 0, 1, 'OUTLET_PICKUP_OVS', 1);

INSERT INTO DELIVERY_TPL_DETAIL_LIVE (DELIVERYTPLDETAILID, ISAPPLICABLE, ISALLOWFORGA, EXPIRYDATE, EXPIRYOPTION, EXPIRYRULEVALUE, EXPIRYRULEUNIT, EXPIRYWINDOW, EXPIRYHOURS, EXPIRYMINUTES, DELIVERY_METHOD_TEMPLATE_ID, DELIVERY_METHOD_ID) VALUES (55172, 'T', 'T', null, 2, 1, null, 1, 18, 0, 8234, 98);
INSERT INTO DELIVERY_TPL_DETAIL_LIVE (DELIVERYTPLDETAILID, ISAPPLICABLE, ISALLOWFORGA, EXPIRYDATE, EXPIRYOPTION, EXPIRYRULEVALUE, EXPIRYRULEUNIT, EXPIRYWINDOW, EXPIRYHOURS, EXPIRYMINUTES, DELIVERY_METHOD_TEMPLATE_ID, DELIVERY_METHOD_ID) VALUES (55173, 'T', 'T', null, 1, 10, 1, 1, null, null, 8234, 52);
INSERT INTO DELIVERY_TPL_DETAIL_LIVE (DELIVERYTPLDETAILID, ISAPPLICABLE, ISALLOWFORGA, EXPIRYDATE, EXPIRYOPTION, EXPIRYRULEVALUE, EXPIRYRULEUNIT, EXPIRYWINDOW, EXPIRYHOURS, EXPIRYMINUTES, DELIVERY_METHOD_TEMPLATE_ID, DELIVERY_METHOD_ID) VALUES (55174, 'T', 'T', null, 1, 3, 2, 2, null, null, 8234, 3);
INSERT INTO DELIVERY_TPL_DETAIL_LIVE (DELIVERYTPLDETAILID, ISAPPLICABLE, ISALLOWFORGA, EXPIRYDATE, EXPIRYOPTION, EXPIRYRULEVALUE, EXPIRYRULEUNIT, EXPIRYWINDOW, EXPIRYHOURS, EXPIRYMINUTES, DELIVERY_METHOD_TEMPLATE_ID, DELIVERY_METHOD_ID) VALUES (55175, 'T', 'T', null, 2, 1, null, 1, 18, 0, 8234, 47);
INSERT INTO DELIVERY_TPL_DETAIL_LIVE (DELIVERYTPLDETAILID, ISAPPLICABLE, ISALLOWFORGA, EXPIRYDATE, EXPIRYOPTION, EXPIRYRULEVALUE, EXPIRYRULEUNIT, EXPIRYWINDOW, EXPIRYHOURS, EXPIRYMINUTES, DELIVERY_METHOD_TEMPLATE_ID, DELIVERY_METHOD_ID) VALUES (55176, 'T', 'T', null, 1, 10, 1, 1, null, null, 8234, 1);
INSERT INTO DELIVERY_TPL_DETAIL_LIVE (DELIVERYTPLDETAILID, ISAPPLICABLE, ISALLOWFORGA, EXPIRYDATE, EXPIRYOPTION, EXPIRYRULEVALUE, EXPIRYRULEUNIT, EXPIRYWINDOW, EXPIRYHOURS, EXPIRYMINUTES, DELIVERY_METHOD_TEMPLATE_ID, DELIVERY_METHOD_ID) VALUES (55177, 'T', 'T', null, 1, 10, 1, 1, null, null, 8234, 60);
INSERT INTO DELIVERY_TPL_DETAIL_LIVE (DELIVERYTPLDETAILID, ISAPPLICABLE, ISALLOWFORGA, EXPIRYDATE, EXPIRYOPTION, EXPIRYRULEVALUE, EXPIRYRULEUNIT, EXPIRYWINDOW, EXPIRYHOURS, EXPIRYMINUTES, DELIVERY_METHOD_TEMPLATE_ID, DELIVERY_METHOD_ID) VALUES (55178, 'T', 'T', null, 2, 1, null, 1, 18, 0, 8234, 40);
INSERT INTO DELIVERY_TPL_DETAIL_LIVE (DELIVERYTPLDETAILID, ISAPPLICABLE, ISALLOWFORGA, EXPIRYDATE, EXPIRYOPTION, EXPIRYRULEVALUE, EXPIRYRULEUNIT, EXPIRYWINDOW, EXPIRYHOURS, EXPIRYMINUTES, DELIVERY_METHOD_TEMPLATE_ID, DELIVERY_METHOD_ID) VALUES (65245, 'T', 'T', null, 1, 1, 1, 1, null, null, 8234, 45);

INSERT INTO DELIVERY_METHOD_TEMPLATE_LIVE (DELIVERYMETHODTEMPLATEID, COMPLETESTATUS, DELIVERYMETHODTEMPLATENAME, GLOBALTEMPLATEID, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY) VALUES (8234, 2, 'Standard', 2385, TO_TIMESTAMP('2016-10-25 18:38:00', 'YYYY-MM-DD HH24:MI:SS'), 8194, TO_TIMESTAMP('2016-10-25 18:38:00', 'YYYY-MM-DD HH24:MI:SS'), 8194);

INSERT INTO DELIVERY_TPL_PRDT_LIVE (DELIVERYTPLPRDTID, DELIVERY_METHOD_TEMPLATE_ID, PRODUCT_ID) VALUES (149247, 8234, 245634);

INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (25, 1, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (39, 2, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (23, 3, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (30, 20, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (229, 38, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (26, 40, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (27, 43, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (28, 44, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (462, 45, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (22, 47, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (33, 48, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (32, 51, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (34, 52, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (29, 53, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (38, 54, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (40, 55, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (24, 56, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (36, 58, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (35, 59, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (230, 60, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (231, 61, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (337, 102, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (329, 103, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (328, 104, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (348, 105, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (363, 108, 11);
INSERT INTO PROFILE_DELIVERY_METHOD (PROFILEDELIVERYMETHODID, DELIVERY_METHOD_ID, PROFILE_INFO_ID) VALUES (457, 113, 11);