truncate table master_code_table;
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (655, 'Solicitation Label', 1, 'UnsubscribeLabel', 'Do Not Sign Up');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (654, 'Solicitation Label', 1, 'TenantLabel', 'SISTIC.com Pte Ltd');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (652, 'Solicitation Type', 1, 'Venue', '4');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (653, 'Solicitation Type', 1, 'Unsubscribe', '5');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (666, 'Solicitation Type', 1, 'OrganiserPhone', '8');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (667, 'Solicitation Type', 1, 'OrganiserPost', '9');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (650, 'Solicitation Type', 1, 'Tenant', '1');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (661, 'Solicitation Type', 1, 'PromoterDirectMailLocal', '7');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (660, 'Solicitation Type', 1, 'PromoterSubEmail', '6');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (651, 'Solicitation Type', 1, 'Promoter', '2');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (657, 'Solicitation Type', 1, 'Promoter SMS', '3');

truncate table ORGANIZATION;
INSERT INTO ORGANIZATION (ORGANIZATIONID, ORGANIZATIONNAME, REGISTRATIONNO, ISTENANT, KEYALIAS, ENCRYPTIONALGORITHM, ORGANIZATIONURL, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY) VALUES (1, 'SISTIC.com Pte Ltd', '20-0006659-E', 'T', '1', 'RSA', null, TO_TIMESTAMP('2013-09-25 16:42:09', 'YYYY-MM-DD HH24:MI:SS'), 1, null, null);
INSERT INTO ORGANIZATION (ORGANIZATIONID, ORGANIZATIONNAME, REGISTRATIONNO, ISTENANT, KEYALIAS, ENCRYPTIONALGORITHM, ORGANIZATIONURL, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY) VALUES (2, 'The Esplanade Co Ltd', '19-9205206-G', 'F', '2', 'RSA', 'https://www.esplanade.com/', TO_TIMESTAMP('2013-09-25 16:42:09', 'YYYY-MM-DD HH24:MI:SS'), 1, TO_TIMESTAMP('2015-12-10 10:00:59', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO ORGANIZATION (ORGANIZATIONID, ORGANIZATIONNAME, REGISTRATIONNO, ISTENANT, KEYALIAS, ENCRYPTIONALGORITHM, ORGANIZATIONURL, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY) VALUES (36, 'Raffles Hotel', null, 'F', null, null, null, TO_TIMESTAMP('2013-09-25 16:42:09', 'YYYY-MM-DD HH24:MI:SS'), 1, null, null);
INSERT INTO ORGANIZATION (ORGANIZATIONID, ORGANIZATIONNAME, REGISTRATIONNO, ISTENANT, KEYALIAS, ENCRYPTIONALGORITHM, ORGANIZATIONURL, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY) VALUES (142, 'The Dream Academy Productions Pte Ltd', null, 'F', null, null, null, TO_TIMESTAMP('2013-09-25 16:42:09', 'YYYY-MM-DD HH24:MI:SS'), 1, null, null);
INSERT INTO ORGANIZATION (ORGANIZATIONID, ORGANIZATIONNAME, REGISTRATIONNO, ISTENANT, KEYALIAS, ENCRYPTIONALGORITHM, ORGANIZATIONURL, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY) VALUES (766, 'MediaCorp VizPro International Pte Ltd', null, 'F', null, null, 'http://www.vizpro.sg/', TO_TIMESTAMP('2013-09-25 16:42:09', 'YYYY-MM-DD HH24:MI:SS'), 1, TO_TIMESTAMP('2015-10-29 19:39:30', 'YYYY-MM-DD HH24:MI:SS'), 30);
INSERT INTO ORGANIZATION (ORGANIZATIONID, ORGANIZATIONNAME, REGISTRATIONNO, ISTENANT, KEYALIAS, ENCRYPTIONALGORITHM, ORGANIZATIONURL, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY) VALUES (1243, 'Woohoo! Experience Pte Ltd', null, 'F', null, null, null, TO_TIMESTAMP('2013-09-25 16:42:09', 'YYYY-MM-DD HH24:MI:SS'), 1, null, null);
INSERT INTO ORGANIZATION (ORGANIZATIONID, ORGANIZATIONNAME, REGISTRATIONNO, ISTENANT, KEYALIAS, ENCRYPTIONALGORITHM, ORGANIZATIONURL, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY) VALUES (1244, 'National Parks Board', null, 'F', null, null, null, TO_TIMESTAMP('2013-09-25 16:42:09', 'YYYY-MM-DD HH24:MI:SS'), 1, null, null);

truncate table PATRON_PROFILE;
INSERT INTO PATRON_PROFILE (PATRONPROFILEID, IDENTITYNO, ACCNO, STATUS, FIRSTNAME, LASTNAME, EMAILADDRESS, ISRECEIVETICKETINGAGENT, ISRECEIVEPROMOTER, ISRECEIVEVENUE, ISBILLINGADDRESSSAMEASMAILING, ISDONOTSIGNUP, ORGANIZATIONNAME, COMPANYID, COMPANYNAME, EMPLOYEEID, GUESTOF, EXTERNALID, ACCTREMARK, ACC_TYPE_MCT_ID, GENDER_MCT_ID, TITLE_MCT_ID, NATIONALITY, COUNTRYOFRESIDENCE, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY, IDENTITY_NO_TYPE_MCT_ID)
VALUES (1921979, 'DSAD4554435', 5084129, 1, 'SHAFIE TESTING', 'PREPROD TEST', 'shafiesistictest@gmail.com', 'T', 'T', 'T', 'F', 'F', null, null, null, null, null, null, null, 90, null, null, 'SG', 'SG', TO_TIMESTAMP('2016-11-03 18:35:29', 'YYYY-MM-DD HH24:MI:SS'), 1601, TO_TIMESTAMP('2016-11-08 17:51:04', 'YYYY-MM-DD HH24:MI:SS'), 59, 647);

truncate table PATRON_SOLICITATION;
INSERT INTO PATRON_SOLICITATION (PATRONSOLICITATIONID, PATRON_PROFILE_ID, SOLICITATION_TYPE_MCT_ID, SOLICITATION_LABEL_MCT_ID, ORGANIZATION_ID, SUBSCRIPTIONSTATUS, UPDATEDDATE, UPDATED_BY) VALUES (961, 1921979, 651, null, 142, 0, TO_TIMESTAMP('2014-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1209);
INSERT INTO PATRON_SOLICITATION (PATRONSOLICITATIONID, PATRON_PROFILE_ID, SOLICITATION_TYPE_MCT_ID, SOLICITATION_LABEL_MCT_ID, ORGANIZATION_ID, SUBSCRIPTIONSTATUS, UPDATEDDATE, UPDATED_BY) VALUES (962, 1921979, 651, null, 766, 0, TO_TIMESTAMP('2014-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1209);
INSERT INTO PATRON_SOLICITATION (PATRONSOLICITATIONID, PATRON_PROFILE_ID, SOLICITATION_TYPE_MCT_ID, SOLICITATION_LABEL_MCT_ID, ORGANIZATION_ID, SUBSCRIPTIONSTATUS, UPDATEDDATE, UPDATED_BY) VALUES (963, 1921979, 651, null, 1243, 0, TO_TIMESTAMP('2014-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1209);
INSERT INTO PATRON_SOLICITATION (PATRONSOLICITATIONID, PATRON_PROFILE_ID, SOLICITATION_TYPE_MCT_ID, SOLICITATION_LABEL_MCT_ID, ORGANIZATION_ID, SUBSCRIPTIONSTATUS, UPDATEDDATE, UPDATED_BY) VALUES (964, 1921979, 650, 654, 1, 0, TO_TIMESTAMP('2014-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1209);
INSERT INTO PATRON_SOLICITATION (PATRONSOLICITATIONID, PATRON_PROFILE_ID, SOLICITATION_TYPE_MCT_ID, SOLICITATION_LABEL_MCT_ID, ORGANIZATION_ID, SUBSCRIPTIONSTATUS, UPDATEDDATE, UPDATED_BY) VALUES (965, 1921979, 652, null, 2, 0, TO_TIMESTAMP('2014-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1209);
INSERT INTO PATRON_SOLICITATION (PATRONSOLICITATIONID, PATRON_PROFILE_ID, SOLICITATION_TYPE_MCT_ID, SOLICITATION_LABEL_MCT_ID, ORGANIZATION_ID, SUBSCRIPTIONSTATUS, UPDATEDDATE, UPDATED_BY) VALUES (966, 1921979, 652, null, 36, 0, TO_TIMESTAMP('2014-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1209);
INSERT INTO PATRON_SOLICITATION (PATRONSOLICITATIONID, PATRON_PROFILE_ID, SOLICITATION_TYPE_MCT_ID, SOLICITATION_LABEL_MCT_ID, ORGANIZATION_ID, SUBSCRIPTIONSTATUS, UPDATEDDATE, UPDATED_BY) VALUES (967, 1921979, 661, null, 1244, 0, TO_TIMESTAMP('2014-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1209);
INSERT INTO PATRON_SOLICITATION (PATRONSOLICITATIONID, PATRON_PROFILE_ID, SOLICITATION_TYPE_MCT_ID, SOLICITATION_LABEL_MCT_ID, ORGANIZATION_ID, SUBSCRIPTIONSTATUS, UPDATEDDATE, UPDATED_BY) VALUES (968, 1921979, 652, null, 1244, 0, TO_TIMESTAMP('2014-06-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1209);

truncate table PRODUCT_LIVE;
INSERT INTO PRODUCT_LIVE (PRODUCTID, PRODUCT_GROUP_ID, PRODUCTNAME, PRODUCTCODE, GLCODE, DESCRIPTION, REMARKS, KEYWORDSEARCH, REPORTVISIBILITY, FINANCIALREPORTVISIBILITY, PRODUCTOWNER, WEIGHT, SALESSTATUS, ACTIVATIONSTATUS, MAXTICKETSAPPL, STARTDATE, ENDDATE, CREATED_BY, CREATEDDATE, UPDATED_BY, UPDATEDDATE, STOP_SALES_REASON_MCT_ID, FESTIVAL_CODE_ID, SPAN_CODE_MCT_ID, VENUE_ID, VENUELAYOUTCONFIG_ID, SALESPIC, EVENTBUILDER)
VALUES (264172, 22713, 'New B.E. Testing Event - GA Seating ', 'efpf1706120900', 'NBETEGA2017', null, null, 'New B.E. Testing Event - GA Seating', 'T', 'T', 'Yangfang', null, 0, 1, null, TO_TIMESTAMP('2017-06-12 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), null, 54, TO_TIMESTAMP('2017-02-07 13:35:44', 'YYYY-MM-DD HH24:MI:SS'), 54, TO_TIMESTAMP('2017-02-07 13:35:44', 'YYYY-MM-DD HH24:MI:SS'), null, null, 30, 7751, 347408, null, null);


truncate table PRODUCT_GROUP_LIVE;
INSERT INTO PRODUCT_GROUP_LIVE (PRODUCTGROUPID, PRODUCTGROUPNAME, PRODUCTGROUPCODE, GLCODE, DESCRIPTION, REMARKS, ISTAXINCLUSIVE, TAX_PERCENT_ID, KEYWORDSEARCH, PORTALURL, REPORTVISIBILITY, FINANCIALREPORTVISIBILITY, PRODUCTOWNER, INTERNETCONTENTCODE, CREATED_BY, CREATEDDATE, UPDATED_BY, UPDATEDDATE, WEIGHT, FESTIVAL_CODE_ID, CATEGORY_CODE_MCT_ID, SPAN_CODE_MCT_ID, SALESPIC, EVENTBUILDER)
VALUES (22713, 'New B.E. Testing Event - GA Seating', 'NBETEGA2017', 'NBETEGA2017', null, null, 'T', 1, 'New B.E. Testing Event - GA Seating', null, 'T', 'T', 'Yangfang', 'NBETEGA2017', 54, TO_TIMESTAMP('2017-02-07 13:35:39', 'YYYY-MM-DD HH24:MI:SS'), 54, TO_TIMESTAMP('2017-02-07 13:35:39', 'YYYY-MM-DD HH24:MI:SS'), null, null, 26, 30, null, 'Yangfang');


truncate table PRDT_GROUP_PROMOTER_LIVE;
INSERT INTO PRDT_GROUP_PROMOTER_LIVE (PRDTGRPPROMOTERID, PRDT_GRP_ID, PROMOTER_ID, PROMOTERGLCODE) VALUES (13331, 22713, 107, null);

truncate table VENUE;
INSERT INTO VENUE (VENUEID, LOCATION_ID, VENUENAME, VENUEALIAS, VENUECAPACITY, REMARKS, UPDATED_BY, UPDATEDDATE, CREATEDDATE, CREATED_BY, STATUS, VENUEURL)
VALUES (7751, 5550, '72-13', '72-13', 150, null, 1739, TO_TIMESTAMP('2016-04-20 13:44:43', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2016-04-20 13:44:43', 'YYYY-MM-DD HH24:MI:SS'), 1739, 1, 'http://www.72-13.com/');

truncate table LOCATION;
INSERT INTO LOCATION (LOCATIONID, ORGANIZATION_ID, LOCATIONNAME, PRINTABLELOCATIONNAME, DISPLAYALIAS, ADDRESS, REMARKS, LOCATIONALIAS, MAILADDRESS, STATUS, UPDATEDDATE, UPDATED_BY, CREATEDDATE, CREATED_BY, LATITUDE, LONGITUDE)
VALUES (5550, 37, '72-13', '72-13', null, '72-13 Mohamed Sultan Road, Singapore 239007', null, null, null, '1', TO_TIMESTAMP('2016-04-20 13:44:03', 'YYYY-MM-DD HH24:MI:SS'), 1739, TO_TIMESTAMP('2016-04-20 13:44:03', 'YYYY-MM-DD HH24:MI:SS'), 1739, 1.291420, 103.840140);