--Prepare test data
TRUNCATE TABLE PROFILE_PAYMENT_METHOD;
INSERT INTO PROFILE_PAYMENT_METHOD (PROFILEPAYMENTID, PAYMENT_METHOD_ID, PROFILE_INFO_ID)
VALUES (122, 109, 11);
--SELECT * FROM profile_payment_method WHERE  PAYMENT_METHOD_ID IN (109) AND PROFILE_PAYMENT_METHOD.PROFILE_INFO_ID = 11;
TRUNCATE TABLE PAYMENT_METHOD;
INSERT INTO PAYMENT_METHOD (PAYMENTMETHODID, PAYMENT_GATEWAY_ID, DESCRIPTION, INTEGRATED, ORDERMETHOD, PAYMENTMETHODNAME, PAYMENTTYPE, PAYMENTMETHODCODE, UNPAID, ORGANIZATION_ID, VALIDFORREPLACE, ISALTERNATEPAYMENT, PAYMENTMETHODTYPESHORT, ISMASSPULL, ACCPACACCTCODE)
VALUES
  (109, 1, 'MASTER Card 2', 1, 4, 'MASTER Card 2', 'MasterCard', 'MASTER', 0, NULL, 'T', '1', 'MC',
   NULL, '30510');
--SELECT * FROM PAYMENT_METHOD WHERE PAYMENT_METHOD.PAYMENTMETHODID IN (109) ;
TRUNCATE TABLE PAYMENT_TPL_DETAIL_LIVE;
INSERT INTO PAYMENT_TPL_DETAIL_LIVE (PAYMENTTPLDETAILID, PAYMENT_METHOD_TEMPLATE_ID, PAYMENT_METHOD_ID)
VALUES (20069, 1471, 109);
INSERT INTO PAYMENT_TPL_DETAIL_LIVE (PAYMENTTPLDETAILID, PAYMENT_METHOD_TEMPLATE_ID, PAYMENT_METHOD_ID)
VALUES (23163, 1665, 109);
--SELECT * FROM payment_tpl_detail WHERE PAYMENT_METHOD_ID = 109;
TRUNCATE TABLE PAYMENT_METHOD_TEMPLATE_LIVE;
INSERT INTO PAYMENT_METHOD_TEMPLATE_LIVE (PAYMENTMETHODTEMPLATEID, COMPLETESTATUS, PAYMENTMETHODTEMPLATENAME, GLOBALTEMPLATEID, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY)
VALUES (1471, 2, 'Standard', 550, TO_TIMESTAMP('2015-05-14 16:39:39', 'YYYY-MM-DD HH24:MI:SS'), 80,
        TO_TIMESTAMP('2015-05-14 16:39:39', 'YYYY-MM-DD HH24:MI:SS'), 80);
INSERT INTO PAYMENT_METHOD_TEMPLATE_LIVE (PAYMENTMETHODTEMPLATEID, COMPLETESTATUS, PAYMENTMETHODTEMPLATENAME, GLOBALTEMPLATEID, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY)
VALUES
  (1665, 2, 'Standard', 550, TO_TIMESTAMP('2015-04-29 10:51:44', 'YYYY-MM-DD HH24:MI:SS'), 1427,
   TO_TIMESTAMP('2015-04-29 10:51:44', 'YYYY-MM-DD HH24:MI:SS'), 1427);
--SELECT * FROM payment_method_template_live WHERE PAYMENTMETHODTEMPLATEID IN (1471, 1665);
TRUNCATE TABLE PAYMENT_TPL_PRDT_LIVE;
INSERT INTO PAYMENT_TPL_PRDT_LIVE (PAYMENTTPLPRDTID, PAYMENT_METHOD_TEMPLATE_ID, PRODUCT_ID)
VALUES (24153, 1471, 120702);
INSERT INTO PAYMENT_TPL_PRDT_LIVE (PAYMENTTPLPRDTID, PAYMENT_METHOD_TEMPLATE_ID, PRODUCT_ID)
VALUES (24152, 1471, 120701);
--SELECT * FROM payment_tpl_prdt_live WHERE PAYMENT_METHOD_TEMPLATE_ID IN (1471, 1665);
TRUNCATE TABLE PRODUCT_LIVE;
INSERT INTO PRODUCT_LIVE (PRODUCTID, PRODUCT_GROUP_ID, PRODUCTNAME, PRODUCTCODE, GLCODE, DESCRIPTION, REMARKS, KEYWORDSEARCH, REPORTVISIBILITY, FINANCIALREPORTVISIBILITY, PRODUCTOWNER, WEIGHT, SALESSTATUS, ACTIVATIONSTATUS, MAXTICKETSAPPL, STARTDATE, ENDDATE, CREATED_BY, CREATEDDATE, UPDATED_BY, UPDATEDDATE, STOP_SALES_REASON_MCT_ID, FESTIVAL_CODE_ID, SPAN_CODE_MCT_ID, VENUE_ID, VENUELAYOUTCONFIG_ID, SALESPIC, EVENTBUILDER)
VALUES (120701, 10928,
                'NO SEX, PLEASE - WE''RE BRITISH A Comedy London''s Longest-Ever Running Comedy - 16 Years in the West End (Test)',
                'ejub1505102000', 'cxlno0515', NULL, NULL,
                'NO SEX, PLEASE - WE''RE BRITISH A Comedy London''s Longest-Ever Running Comedy - 16 Years in the West End',
                'T', 'T', 'melodytang', NULL, 3, 1, NULL, TO_TIMESTAMP('2015-05-10 20:00:00',
                                                                       'YYYY-MM-DD HH24:MI:SS'),
                                        NULL, 80, TO_TIMESTAMP('2015-05-14 16:39:40',
                                                               'YYYY-MM-DD HH24:MI:SS'), 80,
                                        TO_TIMESTAMP('2015-05-14 16:39:40',
                                                     'YYYY-MM-DD HH24:MI:SS'), 16, NULL, 30, 651,
        17237, NULL, 'henrykeh');
INSERT INTO PRODUCT_LIVE (PRODUCTID, PRODUCT_GROUP_ID, PRODUCTNAME, PRODUCTCODE, GLCODE, DESCRIPTION, REMARKS, KEYWORDSEARCH, REPORTVISIBILITY, FINANCIALREPORTVISIBILITY, PRODUCTOWNER, WEIGHT, SALESSTATUS, ACTIVATIONSTATUS, MAXTICKETSAPPL, STARTDATE, ENDDATE, CREATED_BY, CREATEDDATE, UPDATED_BY, UPDATEDDATE, STOP_SALES_REASON_MCT_ID, FESTIVAL_CODE_ID, SPAN_CODE_MCT_ID, VENUE_ID, VENUELAYOUTCONFIG_ID, SALESPIC, EVENTBUILDER)
VALUES (120702, 10928,
                'NO SEX, PLEASE - WE''RE BRITISH A Comedy London''s Longest-Ever Running Comedy - 16 Years in the West End (Test)',
                'ejub1505152000', 'sex0515', NULL, NULL,
                'NO SEX, PLEASE - WE''RE BRITISH A Comedy London''s Longest-Ever Running Comedy - 16 Years in the West End',
                'T', 'T', 'melodytang', NULL, 0, 1, NULL, TO_TIMESTAMP('2015-05-15 20:00:00',
                                                                       'YYYY-MM-DD HH24:MI:SS'),
                                        NULL, 80, TO_TIMESTAMP('2015-05-14 16:39:40',
                                                               'YYYY-MM-DD HH24:MI:SS'), 80,
                                        TO_TIMESTAMP('2015-05-14 16:39:40',
                                                     'YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 30, 651,
        17238, NULL, 'henrykeh');
--SELECT * FROM product_live WHERE PRODUCTID IN (120702, 120701);