--Product & Price Related
TRUNCATE TABLE PRODUCT_LIVE;
TRUNCATE TABLE PRODUCT_GROUP_LIVE;
TRUNCATE TABLE PRICE_CATEGORY_LIVE;
TRUNCATE TABLE PROFILE_INFO;
TRUNCATE TABLE GROUP_INFO;
TRUNCATE TABLE USER_GROUP;
TRUNCATE TABLE TRANSACTION_CODE;
TRUNCATE TABLE MASTER_CODE_TABLE;

INSERT INTO PRODUCT_LIVE (PRODUCTID, PRODUCT_GROUP_ID, PRODUCTNAME, PRODUCTCODE, GLCODE, DESCRIPTION, REMARKS, KEYWORDSEARCH, REPORTVISIBILITY, FINANCIALREPORTVISIBILITY, PRODUCTOWNER, WEIGHT, SALESSTATUS, ACTIVATIONSTATUS, MAXTICKETSAPPL, STARTDATE, ENDDATE, CREATED_BY, CREATEDDATE, UPDATED_BY, UPDATEDDATE, STOP_SALES_REASON_MCT_ID, FESTIVAL_CODE_ID, SPAN_CODE_MCT_ID, VENUE_ID, VENUELAYOUTCONFIG_ID, SALESPIC, EVENTBUILDER) VALUES (245634, 16017, 'Lee Kong Chian Natural History Museum (Aug16) (Test)', 'elkc1611011600', 'lkc0816', null, null, 'Lee Kong Chian Natural History Museum (Aug16)', 'T', 'T', 'Zhiqi', null, 0, 1, null, sysdate+31, null, 8194, TO_TIMESTAMP('2016-10-25 18:38:07', 'YYYY-MM-DD HH24:MI:SS'), 8194, TO_TIMESTAMP('2016-10-25 18:38:07', 'YYYY-MM-DD HH24:MI:SS'), null, null, 30, 3850, 343732, null, null);

INSERT INTO product_group_live (PRODUCTGROUPID,PRODUCTGROUPNAME,PRODUCTGROUPCODE,GLCODE,DESCRIPTION,REMARKS,ISTAXINCLUSIVE,TAX_PERCENT_ID,KEYWORDSEARCH,PORTALURL,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,INTERNETCONTENTCODE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,WEIGHT,FESTIVAL_CODE_ID,CATEGORY_CODE_MCT_ID,SPAN_CODE_MCT_ID,SALESPIC,EVENTBUILDER) 
VALUES(16017,'FRENCH MOVIES 2013 (Test)','french1013','french1013',NULL,NULL,'T',1,'French Movie 2013',NULL,'T','T','Melody Tang','french1013',28,TO_TIMESTAMP('2016-10-25 18:37:58', 'YYYY-MM-DD HH24:MI:SS'),28,TO_TIMESTAMP('2016-10-25 18:37:58', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,26,NULL,NULL,NULL);
INSERT INTO product_group_live (PRODUCTGROUPID,PRODUCTGROUPNAME,PRODUCTGROUPCODE,GLCODE,DESCRIPTION,REMARKS,ISTAXINCLUSIVE,TAX_PERCENT_ID,KEYWORDSEARCH,PORTALURL,REPORTVISIBILITY,FINANCIALREPORTVISIBILITY,PRODUCTOWNER,INTERNETCONTENTCODE,CREATED_BY,CREATEDDATE,UPDATED_BY,UPDATEDDATE,WEIGHT,FESTIVAL_CODE_ID,CATEGORY_CODE_MCT_ID,SPAN_CODE_MCT_ID,SALESPIC,EVENTBUILDER) 
VALUES(49,'Spanish Movie Fiesta 2013 (Test)','spain1113','spain1113',NULL,NULL,'T',1,'Spanish Movie Fiesta 2013 (Test)','http://192.168.10.238/events/spain1113','T','T','allison','spain1113',30,TO_TIMESTAMP('2016-10-25 18:37:58', 'YYYY-MM-DD HH24:MI:SS'),30,TO_TIMESTAMP('2016-10-25 18:37:58', 'YYYY-MM-DD HH24:MI:SS'),NULL,NULL,26,NULL,NULL,NULL);

INSERT INTO PRICE_CATEGORY_LIVE (PRICECATEGORYID, PRICECATEGORYNAME, PRICECATEGORYNUMBER, PRODUCTGROUP_ID, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY) VALUES (12176, 'Cat 1', 1, 16017, TO_TIMESTAMP('2016-10-25 18:37:58', 'YYYY-MM-DD HH24:MI:SS'), 8194, TO_TIMESTAMP('2016-10-25 18:37:58', 'YYYY-MM-DD HH24:MI:SS'), 8194);

--Next set of sql
INSERT INTO PROFILE_INFO (PROFILEINFOID, PROFILECODE, PROFILENAME, SELLERSTATUS, PROFILE_CHANNEL_ID, ISPAYMENTOFFLINE, PAYMENTMODE, IMMEDIATEPRINTINGSTATUS, CREATED_BY, CREATEDDATE, UPDATED_BY, UPDATEDDATE, USETHERMALPRINTER) VALUES (11, ' ', 'SISTIC Internet', 'Y', 1, '0', 1, 'N', 4, TO_TIMESTAMP('2013-10-02 15:53:15', 'YYYY-MM-DD HH24:MI:SS'), 3, TO_TIMESTAMP('2016-05-20 19:23:21', 'YYYY-MM-DD HH24:MI:SS'), 'N');

INSERT INTO GROUP_INFO (GROUPINFOID, GROUPNAME, GROUPCODE, STATUS, GROUP_TYPE_ID, ISDEFAULT, CREATED_BY, CREATEDDATE, UPDATED_BY, UPDATEDDATE) VALUES (203, 'Standard_User_Fee_Group', 'Standard_User_Fee_Group', 1, 2, 'F', 1, TO_TIMESTAMP('2013-09-25 18:29:02', 'YYYY-MM-DD HH24:MI:SS'), 4, TO_TIMESTAMP('2016-08-01 18:02:36', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO USER_GROUP (USERGROUPID, GROUP_INFO_ID, PROFILE_INFO_ID, USER_INFO_ID) VALUES (84, 203, 11, 59);
INSERT INTO USER_GROUP (USERGROUPID, GROUP_INFO_ID, PROFILE_INFO_ID, USER_INFO_ID) VALUES (3311, 203, 11, 1198);

INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (11, 'Transaction Type', 1, 'Purchase', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (7, 'FEE Category', 1, 'Flat Based', '1');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (8, 'FEE Category', 1, 'Delivery Based', '2');
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (61, 'Levy By', 1, 'Outlet', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (62, 'Levy By', 1, 'Show', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (60, 'Levy By', 1, 'Address', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (63, 'Levy By', 1, 'Per Ticket', null);
INSERT INTO MASTER_CODE_TABLE (MASTERCODEID, CATEGORYCODE, STATUS, DESCRIPTION1, DESCRIPTION2) VALUES (64, 'Levy By', 1, 'Transaction', null);

INSERT INTO TRANSACTION_CODE (TRANSACTIONCODEID, TXN_CODE_MCT_ID, SALES_STATUS_MCT_ID, TXNREASON, TXNDESCRIPTION, CREATED_BY, CREATEDDATE, UPDATED_BY, UPDATEDDATE) VALUES (1, 11, null, 'Sales', 'Sales', 1, TO_TIMESTAMP('2013-09-25 15:24:37', 'YYYY-MM-DD HH24:MI:SS'), 1, TO_TIMESTAMP('2013-09-25 15:24:37', 'YYYY-MM-DD HH24:MI:SS'));
