TRUNCATE TABLE sales_seat_inventory;
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555775, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555776, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555777, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555778, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555779, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555780, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555781, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555782, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555783, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);
INSERT INTO SALES_SEAT_INVENTORY (SALESSEATINVENTORYID, PRODUCT_ID, RANK, SEATSALESSTATUS, TICKETABLE, PRICE_CAT_ID, PRICE_CLASS_ID, PATRON_ID, RESERVEEXPIRYDATE, SYSTEM_SALE_CODE_ID, HOLD_BY, HOLDDATE, SOLD_BY, SOLDDATE, UPDATEDTIME, UPDATED_BY, HOLDREASON, HOLDEXPIRYNOTIFIED, SECTIONRANK, SPANKEY, VENUE_SEAT_LC_ID, VENUE_SECTION_LC_ID, SALESCYCLESTARTTIME, PACKAGE_ID, PACKAGEREQUIREMENT_ID, PRICEVALUE, SESSIONID, HOLDEXPIRYDATE)
VALUES
  (121555784, 245634, 0, 1, 1, 12176, NULL, NULL, systimestamp, NULL, NULL, NULL, NULL, NULL,
                                                                            systimestamp,
                                                                            1437, NULL, NULL, 0,
                                                                            NULL,
                                                                            NULL, 356882, NULL,
   NULL,
   NULL, NULL, NULL, NULL);


truncate TABLE PRICE_MODEL_TPL_PRDT_LIVE;
INSERT INTO PRICE_MODEL_TPL_PRDT_LIVE (PRICEMODELTPLPRDTID, PRICE_MODEL_TEMPLATE_ID, PRODUCT_ID, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY)
VALUES (163645, 13832, 245634, TO_TIMESTAMP('2017-01-03 12:21:05', 'YYYY-MM-DD HH24:MI:SS'), 1031, TO_TIMESTAMP('2017-01-03 12:21:05', 'YYYY-MM-DD HH24:MI:SS'), 1031);

truncate TABLE PMT_ROW_LIVE;
INSERT INTO PMT_ROW_LIVE (PMTROWID, TICKETPRINTALIAS, ISDISPLAYFORSALES, ISSTANDARD, RANKING, QUOTA, PRICECLASS_ID, PRICEMODELTEMPLATE_ID, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY)
VALUES (141571, null, 'T', 'T', 3, 0, 75586, 13832, TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031, TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031);
INSERT INTO PMT_ROW_LIVE (PMTROWID, TICKETPRINTALIAS, ISDISPLAYFORSALES, ISSTANDARD, RANKING, QUOTA, PRICECLASS_ID, PRICEMODELTEMPLATE_ID, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY)
VALUES (141561, null, 'T', 'F', 3, 0, 75616, 13832, TO_TIMESTAMP('2017-01-03 12:21:00', 'YYYY-MM-DD HH24:MI:SS'), 1031, TO_TIMESTAMP('2017-01-03 12:21:00', 'YYYY-MM-DD HH24:MI:SS'), 1031);

truncate TABLE PRICE_CLASS_LIVE;
INSERT INTO PRICE_CLASS_LIVE (PRICECLASSID, PRICECLASSNAME, PRICECLASSCODE, PRICECLASSDESCRIPTION, ISCOMPLIMENTARYTICKET, ISPACKAGECLASS, DISCOUNTRULE, PRICEVALUERULE, SPANQUOTA, BUYTICKETSQUANTITY, GETTICKETQUANTITY, OFFVALUE, PVPRICECLASS_ID, DISCOUNTPRICECLASS_ID, TYPEOFDISCOUNT_MCT_ID, PROMOTIONPASSWORD_ID, CREDITCARDRANGE_ID, PRODUCTGROUP_ID, VALIDITY_PERIOD, CHANNELS, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY, ORDERING)
VALUES (75586, 'Standard Adult', 'A', 'Standard Adult', 'F', 'F', 1, 1, 0, 0, 0, 0.00000, null, null, null, null, null, 16017, null, 'All Channel', TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031, TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031, 8);
INSERT INTO PRICE_CLASS_LIVE (PRICECLASSID, PRICECLASSNAME, PRICECLASSCODE, PRICECLASSDESCRIPTION, ISCOMPLIMENTARYTICKET, ISPACKAGECLASS, DISCOUNTRULE, PRICEVALUERULE, SPANQUOTA, BUYTICKETSQUANTITY, GETTICKETQUANTITY, OFFVALUE, PVPRICECLASS_ID, DISCOUNTPRICECLASS_ID, TYPEOFDISCOUNT_MCT_ID, PROMOTIONPASSWORD_ID, CREDITCARDRANGE_ID, PRODUCTGROUP_ID, VALIDITY_PERIOD, CHANNELS, CREATEDDATE, CREATED_BY, UPDATEDDATE, UPDATED_BY, ORDERING)
VALUES (75616, 'S''porean/ PR Adult', 'A1', 'Singaporean/ Permanent Resident (PR)', 'F', 'F', 1, 1, 0, 0, 0, 0.00000, null, null, null, null, null, 16017, null, 'All Channel', TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031, TO_TIMESTAMP('2017-01-03 12:20:59', 'YYYY-MM-DD HH24:MI:SS'), 1031, 3);