INSERT INTO CART_LINE_ITEMS_VIEW (PRODUCTID, PRODUCTNAME, STARTDATE, SEATLEVELALIAS, ROWALIAS, SALESSEATINVENTORYID, SEATNO, SEATSECTIONTYPE, VENUEALIAS, PRICECATALIAS, PRICECLASSCODE, PRICECLASSNAME, PRICECATID, SEATSECTIONID, PRICEVALUE, PROFILE_INFO_ID)
VALUES (254999, 'BILL BAILEY Limboland - Live in Singapore (Test)',
                TO_TIMESTAMP('2016-12-03 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Circle L3', 'UL',
                123002697, 3, 'RS', 'University Cultural Centre Hall, NUS', 'Cat 4', 'A',
        'STANDARD', 2663, 359156, 88.00000, 11);
INSERT INTO CART_LINE_ITEMS_VIEW (PRODUCTID, PRODUCTNAME, STARTDATE, SEATLEVELALIAS, ROWALIAS, SALESSEATINVENTORYID, SEATNO, SEATSECTIONTYPE, VENUEALIAS, PRICECATALIAS, PRICECLASSCODE, PRICECLASSNAME, PRICECATID, SEATSECTIONID, PRICEVALUE, PROFILE_INFO_ID)
VALUES (254999, 'BILL BAILEY Limboland - Live in Singapore (Test)',
                TO_TIMESTAMP('2016-12-03 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Stall L1', 'R',
                123003774, 38, 'RS', 'University Cultural Centre Hall, NUS', 'Cat 2', 'A',
        'STANDARD', 2138, 359168, 128.00000, 11);