TRUNCATE TABLE validate_cart_view;
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75586, 'A', 2, 1, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75616, 'A1', 2, 1, 2, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75597, 'D', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75601, 'D1', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75599, 'D2', 2, 1, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75589, 'D3', 2, 1, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75587, 'D4', 2, 1, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75591, 'D5', 2, 1, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75608, 'D9', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75612, 'DA', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75615, 'F', 2, 1, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75605, 'F1', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75592, 'F2', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75596, 'F3', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75611, 'F4', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75593, 'F5', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75598, 'F6', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75588, 'F7', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75600, 'F8', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75613, 'F9', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75614, 'FA', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75595, 'FB', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75603, 'FC', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75602, 'FD', 2, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75610, 'FE', 2, 1, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 75594, 'FF', 2, 1, 0, 0, 0, 0, 0, 0);
INSERT INTO validate_cart_view (PRODUCT_ID, PRICECATEGORYID, PRICECLASSID, PRICECLASSCODE, QUANTITYSTATUS, QUANTITY, MAXIMUMQUANTITY, CHARTQUOTA, ROWQUOTA, PRICECLASSQUOTA, PRICE_CLASS_UNAVAILABLE_SEATS, PRICE_CAT_UNAVAILABLE_SEATS)
VALUES (245634, 12176, 86126, 'PR', 2, 1, 0, 0, 0, 0, 0, 0);